blog/article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

blog/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    
    path('about/', views.about, name='about'),
]

blog/article/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
        
    class Meta:
        ordering = ['-pubDateTime']


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title + '-' + str(self.id)

    class Meta:
        ordering = ['pubDateTime']
   

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from article.models import Article, Comment
from article.forms import ArticleForm


def article(request):
    '''
    Render the article page
    '''
    articles = {}
    for article in Article.objects.all():
        articles.update({article:Comment.objects.filter(article=article)})
    context = {'articles':articles}
    return render(request, 'article/article.html', context)


def articleCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the article page
    '''
    template = 'article/articleCreate.html'
    if request.method == 'GET':
        print(ArticleForm())
        return render(request, template, {'articleForm':ArticleForm()})
    
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})

    print(articleForm)
    articleForm.save()
    messages.success(request, '文章已新增')
    # articleForm.save()
    return redirect('article:article')
    

blog/main/views.py
from django.shortcuts import render


def main(request):
    '''
    Render the main page
    '''
    context = {'like':'Django 很棒'}
    return render(request, 'main/main.html', context)
def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'article/css/article.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
     <h2>歡迎來到我的部落格</h2>
     {% for message in messages %}
      <p class="{{ message.tags }}">{{ message }}</p>
     {% endfor %}
    <p><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>
    {% for article, comments in articles.items %}
      <h3>{{ article.title }}</h3>
      <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
      <div class="articleContent">{{ article.content|linebreaks|truncatechars_html:30 }}</div>
      {% for comment in comments %}
        <div class="commentDiv">
          <span class="comment">{{ comment.content }}</span>
          <br>
          <span class="commentTime">{{ comment.pubDateTime|date:'m月d日 H:i' }}</span>
        </div>
      {% endfor %}
    {% endfor %}
  </body>
</html>

blog/article/templates/article/articleCreate.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'article/css/article.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>新增文章</h2>
    <form method="post" action="{% url 'article:articleCreate' %}">
      {% csrf_token %}
      {{ articleForm.as_p }}
      <input type="submit" value="送出">
    </form>
  </body>
</html>

blog/main/templates/main/about.html
<!doctype html>
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>關於部落格</h2>
    <p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
  </body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>Django 說 -- Hello world!</h2>
    <p>{{ like }}</p>
  </body>
</html>

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>